apiVersion: kfdef.apps.kubeflow.org/v1beta1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: "false"
  clusterName: api-cluster-odh43-52d8-odh43-52d8-example-opentlc-com:6443
  creationTimestamp: null
  name: kfdef
  namespace: kubeflow
spec:
  applications:
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: openshift-operators
      repoRef:
        name: odh-manifests
        path: istio/service-mesh-cluster
    name: servicemesh-cluster
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: odh-manifests
        path: istio/service-mesh-control-plane
    name: servicemesh-control-plane
  - kustomizeConfig:
      repoRef:
        name: odh-manifests
        path: istio/sistio
    name: istio-kubeflow
  - kustomizeConfig:
      overlays:
      - istio
      repoRef:
        name: manifests
        path: common/centraldashboard
    name: centraldashboard
  - kustomizeConfig:
      overlays:
      - istio
      - openshift
      parameters:
      - name: admin
        value: johnDoe@acme.com
      repoRef:
        name: manifests
        path: profiles
    name: profiles
  repos:
  - name: manifests
    uri: https://github.com/opendatahub-io/manifests/archive/v0.7-branch-openshift.tar.gz
  - name: odh-manifests
    uri: https://github.com/vpavlin/odh-kf-manifests/archive/rhservicemesh.tar.gz
  version: v0.7-branch-openshift
status:
  reposCache:
  - localPath: '"kfdef/.cache/manifests/manifests-0.7-branch-openshift"'
    name: manifests
  - localPath: '"kfdef/.cache/odh-manifests/odh-kf-manifests-rhservicemesh"'
    name: odh-manifests
