apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: spark-operator
resources:
- spark-operator.yaml
- jupyterhub-spark-operator-configmap.yaml

configMapGenerator:
- name: spark-operator-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: workerNodeCount
  objref:
    kind: ConfigMap
    name: spark-operator-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.workerNodeCount
- name: masterNodeCount
  objref:
    kind: ConfigMap
    name: spark-operator-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.masterNodeCount
configurations:
- params.yaml
